"""Regenerates the function call graphs in docs/call_graph/ with pyan3 (static analysis)
and renders them with Graphviz `dot`. Run it after any structural change (new module,
function moved or renamed) - docs/execution.md section 5 links to its output.

Outputs (do not edit by hand):
    docs/call_graph/<name>.dot   graph source
    docs/call_graph/<name>.svg   rendered image
    docs/call_graph/<name>.txt   plain-text edge list (diff-friendly)

Graphs:
    full      every module/class/function under src/pdm and how they call each other
    retrain   everything reachable from pdm.training.retrain.retrain (the retrain job)
    drift     everything reachable from pdm.drift.run_drift_check.main (the drift job)
    serving   everything reachable from pdm.serving.app.predict (POST /predict)

pyan3 is approximate: it resolves calls by name, so calls through variables (e.g.
adapter["load"](...)) or into other libraries are not shown. The hand-written call
chains in docs/execution.md fill those gaps.

Requires: pip install pyan3 (requirements-dev.txt) and Graphviz (`dot` on PATH).

Usage:
    python scripts/generate_call_graph.py
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "call_graph"
SOURCES = sorted(str(p.relative_to(ROOT / "src")) for p in (ROOT / "src" / "pdm").rglob("*.py"))

GRAPHS = {
    "full": [],
    "retrain": ["--function", "pdm.training.retrain.retrain", "--direction", "down"],
    "drift": ["--function", "pdm.drift.run_drift_check.main", "--direction", "down"],
    "serving": ["--function", "pdm.serving.app.predict", "--direction", "down"],
}
# --nested-groups, not --grouped: with --grouped, Graphviz 2.43 fails on the full
# package graph ("trouble in init_rank"); nested module groups render fine.
COMMON = ["--uses", "--no-defines", "--colored", "--nested-groups"]


def pyan(args: list[str], fmt: str) -> str:
    pyan3 = shutil.which("pyan3") or str(Path(sys.executable).parent / "pyan3")
    cmd = [pyan3, *SOURCES, f"--{fmt}", *COMMON, *args]
    return subprocess.run(cmd, cwd=ROOT / "src", check=True, capture_output=True, text=True).stdout


def main() -> int:
    if not shutil.which("dot"):
        raise SystemExit("Graphviz `dot` not found on PATH (apt-get install graphviz)")
    OUT.mkdir(parents=True, exist_ok=True)
    header = "// AUTO-GENERATED by scripts/generate_call_graph.py - do not edit by hand\n"
    for name, args in GRAPHS.items():
        # pyan3 puts absolute file paths in node tooltips; keep them repo-relative so the
        # output is the same on every machine.
        dot_src = pyan(args, "dot").replace(f"{ROOT}/", "")
        (OUT / f"{name}.dot").write_text(header + dot_src)
        text = pyan(args, "text")
        (OUT / f"{name}.txt").write_text(
            "# AUTO-GENERATED by scripts/generate_call_graph.py - do not edit by hand\n" + text
        )
        subprocess.run(
            [
                "dot",
                "-Tsvg",
                "-Grankdir=LR",
                str(OUT / f"{name}.dot"),
                "-o",
                str(OUT / f"{name}.svg"),
            ],
            check=True,
            capture_output=True,
        )
        print(f"wrote docs/call_graph/{name}.dot/.svg/.txt")
    return 0


if __name__ == "__main__":
    sys.exit(main())
